### ISSUE TITLE
 so many bugs that it is abnormal

### ISSUE THREAD

**Issue by dwjvbh** [IRMVLab/Point-Mamba#17]
There are too many bugs in this code. It is the code I have run that has so many bugs that it is abnormal. How did the author come up with it??? Make people doubt the correctness of this code!!!!
python segmentation.py --config configs/seg_scannet.yaml SOLVER.gpu  0, SOLVER.alias  scannet SOLVER.dist_url tcp://localhost:10001

**Comment by dwjvbh** [comment]
I am truly disgusted by this code

**Comment by Aristo23333** [comment]
Sorry to hear that. But if you can point out specific problems instead of complaining, maybe we can help further.  Thank you!
