### ISSUE TITLE
Failed building wheel for cyminiball

### ISSUE THREAD

**Issue by Research-Code-123** [IRMVLab/Point-Mamba#20]
Dear Author:

Have you ever met this bug?

      In file included from /root/anaconda3/envs/Point-Mamba/include/python3.10/Python.h:74,
                       from src/_miniball_wrap.cpp:35:
      src/_miniball_wrap.cpp: In function ‘PyObject* __pyx_f_5numpy_PyDataType_SHAPE(PyArray_Descr*)’:
      src/_miniball_wrap.cpp:8712:41: error: ‘PyArray_Descr’ {aka ‘struct _PyArray_Descr’} has no member named ‘subarray’
       8712 |     __Pyx_INCREF(((PyObject*)__pyx_v_d->subarray->shape));
            |                                         ^~~~~~~~
      /root/anaconda3/envs/Point-Mamba/include/python3.10/object.h:112:41: note: in definition of macro ‘_PyObject_CAST’
        112 | #define _PyObject_CAST(op) ((PyObject*)(op))
            |                                         ^~
      src/_miniball_wrap.cpp:1523:27: note: in expansion of macro ‘Py_INCREF’
       1523 |   #define __Pyx_INCREF(r) Py_INCREF(r)
            |                           ^~~~~~~~~
      src/_miniball_wrap.cpp:8712:5: note: in expansion of macro ‘__Pyx_INCREF’
       8712 |     __Pyx_INCREF(((PyObject*)__pyx_v_d->subarray->shape));
            |     ^~~~~~~~~~~~
      src/_miniball_wrap.cpp:8713:38: error: ‘PyArray_Descr’ {aka ‘struct _PyArray_Descr’} has no member named ‘subarray’
       8713 |     __pyx_r = ((PyObject*)__pyx_v_d->subarray->shape);
            |                                      ^~~~~~~~
      error: command '/usr/bin/g++' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for cyminiball
Successfully built mmcv python-hostlist wget
Failed to build cyminiball
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (cyminiball)

Thanks

**Comment by Dreamxxxxxx** [comment]
> Dear Author:
> 
> Have you ever met this bug?
> 
> ```
>   In file included from /root/anaconda3/envs/Point-Mamba/include/python3.10/Python.h:74,
>                    from src/_miniball_wrap.cpp:35:
>   src/_miniball_wrap.cpp: In function ‘PyObject* __pyx_f_5numpy_PyDataType_SHAPE(PyArray_Descr*)’:
>   src/_miniball_wrap.cpp:8712:41: error: ‘PyArray_Descr’ {aka ‘struct _PyArray_Descr’} has no member named ‘subarray’
>    8712 |     __Pyx_INCREF(((PyObject*)__pyx_v_d->subarray->shape));
>         |                                         ^~~~~~~~
>   /root/anaconda3/envs/Point-Mamba/include/python3.10/object.h:112:41: note: in definition of macro ‘_PyObject_CAST’
>     112 | #define _PyObject_CAST(op) ((PyObject*)(op))
>         |                                         ^~
>   src/_miniball_wrap.cpp:1523:27: note: in expansion of macro ‘Py_INCREF’
>    1523 |   #define __Pyx_INCREF(r) Py_INCREF(r)
>         |                           ^~~~~~~~~
>   src/_miniball_wrap.cpp:8712:5: note: in expansion of macro ‘__Pyx_INCREF’
>    8712 |     __Pyx_INCREF(((PyObject*)__pyx_v_d->subarray->shape));
>         |     ^~~~~~~~~~~~
>   src/_miniball_wrap.cpp:8713:38: error: ‘PyArray_Descr’ {aka ‘struct _PyArray_Descr’} has no member named ‘subarray’
>    8713 |     __pyx_r = ((PyObject*)__pyx_v_d->subarray->shape);
>         |                                      ^~~~~~~~
>   error: command '/usr/bin/g++' failed with exit code 1
>   [end of output]
> ```
> 
> note: This error originates from a subprocess, and is likely not a problem with pip. ERROR: Failed building wheel for cyminiball Successfully built mmcv python-hostlist wget Failed to build cyminiball ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (cyminiball)
> 
> Thanks

Hello, I have encountered the same problem. How did you solve it?

**Comment by ColourfulMax** [comment]
Hello, I have encountered the same problem. How did you solve it?
