### ISSUE TITLE
About the different between test/mIoU and test/mIoU_part

### ISSUE THREAD

**Issue by Sylva-Lin** [IRMVLab/Point-Mamba#3]
Hi, thank you for your work! when I trained the model in ScanNet, I found two types of mIoU in the result. Are there any differences between them? And what type of mIoU is the result in your paper?

**Comment by Aristo23333** [comment]
> Hi, thank you for your work! when I trained the model in ScanNet, I found two types of mIoU in the result. Are there any differences between them? And what type of mIoU is the result in your paper?

**Hello, thank you for interested in our work, and indeed our results are calculated to test_mIoU and test_mIoU_part two kinds of results, the latter used in our paper. The main difference between them is that the latter takes into account unimportant mask information such as scene background, in fact, you can read the difference between them in the segmentation.py.**

**Comment by Sylva-Lin** [comment]
> > Hi, thank you for your work! when I trained the model in ScanNet, I found two types of mIoU in the result. Are there any differences between them? And what type of mIoU is the result in your paper?
> 
> **Hello, thank you for interested in our work, and indeed our results are calculated to test_mIoU and test_mIoU_part two kinds of results, the latter used in our paper. The main difference between them is that the latter takes into account unimportant mask information such as scene background, in fact, you can read the difference between them in the segmentation.py.**

Thank you for your reply, I trained Model in ScanNet for 700 Epoch, but the best test_mIoU_part was only 70.26%, which is much lower than the results of the paper with 74.6%. I used a single RTX 3090, other configs are the same as the default. Do you think any reason caused this result?

**Comment by Aristo23333** [comment]
It is important to point out that there are many uncertainties in the training of the Mamba network. Our training has tried under 3 blocks of 4090 and 2 blocks of 4090 in different environments, and there is also a certain error, but almost all of them are above 73%. For your results, I would suggest that you first try to make sure that the environment is as consistent as possible with the reference we provided, and secondly, try to compare multiple training sessions. You may be able to verify this with the eval function and the CPKT we provide.Thank you!

----- 原始邮件 -----
发件人: "Zhenchao Lin" ***@***.***>
收件人: "IRMVLab/Point-Mamba" ***@***.***>
抄送: "Yu Rui Ji" ***@***.***>, "Comment" ***@***.***>
发送时间: 星期六, 2024年 3 月 30日 下午 5:46:05
主题: Re: [IRMVLab/Point-Mamba] About the different between test/mIoU and test/mIoU_part (Issue #3)

> > Hi, thank you for your work! when I trained the model in ScanNet, I found two types of mIoU in the result. Are there any differences between them? And what type of mIoU is the result in your paper?
> 
> **Hello, thank you for interested in our work, and indeed our results are calculated to test_mIoU and test_mIoU_part two kinds of results, the latter used in our paper. The main difference between them is that the latter takes into account unimportant mask information such as scene background, in fact, you can read the difference between them in the segmentation.py.**

Thank you for your reply, I trained Model in ScanNet for 700 Epoch, but the best test_mIoU_part was only 70.26%, which is much lower than the results of the paper with 74.6%. I used a single RTX 3090, other configs are the same as the default. Do you think any reason caused this result?

**Comment by Sylva-Lin** [comment]
> It is important to point out that there are many uncertainties in the training of the Mamba network. Our training has tried under 3 blocks of 4090 and 2 blocks of 4090 in different environments, and there is also a certain error, but almost all of them are above 73%. For your results, I would suggest that you first try to make sure that the environment is as consistent as possible with the reference we provided, and secondly, try to compare multiple training sessions. You may be able to verify this with the eval function and the CPKT we provide.Thank you!
> ----- 原始邮件 ----- 发件人: "Zhenchao Lin" ***@***.***> 收件人: "IRMVLab/Point-Mamba" ***@***.***> 抄送: "Yu Rui Ji" ***@***.***>, "Comment" ***@***.***> 发送时间: 星期六, 2024年 3 月 30日 下午 5:46:05 主题: Re: [IRMVLab/Point-Mamba] About the different between test/mIoU and test/mIoU_part (Issue #3)
> > Hi, thank you for your work! when I trained the model in ScanNet, I found two types of mIoU in the result. Are there any differences between them? And what type of mIoU is the result in your paper? **Hello, thank you for interested in our work, and indeed our results are calculated to test_mIoU and test_mIoU_part two kinds of results, the latter used in our paper. The main difference between them is that the latter takes into account unimportant mask information such as scene background, in fact, you can read the difference between them in the segmentation.py.**
> Thank you for your reply, I trained Model in ScanNet for 700 Epoch, but the best test_mIoU_part was only 70.26%, which is much lower than the results of the paper with 74.6%. I used a single RTX 3090, other configs are the same as the default. Do you think any reason caused this result?
> […](#)
> -- Reply to this email directly or view it on GitHub: [#3 (comment)](https://github.com/IRMVLab/Point-Mamba/issues/3#issuecomment-2027994498) You are receiving this because you commented. Message ID: ***@***.***>

Hi, I tried to use multiple GPUs for training, but the following error emerged, did you meet this question? Could you tell me how to solve it? thank. 
![屏幕截图 2024-04-01 133645](https://github.com/IRMVLab/Point-Mamba/assets/105730616/04835795-1f03-43ef-857b-32b50a5c7a54)

**Comment by Sylva-Lin** [comment]
As I use "find_unused_parameters: True" in your default config, the error is as follows: 
![屏幕截图 2024-04-01 143529](https://github.com/IRMVLab/Point-Mamba/assets/105730616/08fe0946-18ee-4235-a792-a1e0e735d694)

**Comment by Sylva-Lin** [comment]
Hi, Could you reply to my question when you 're free? I would be very grateful for you.



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | Yu Rui ***@***.***> |
| 日期 | 2024年03月30日 20:01 |
| 收件人 | ***@***.***> |
| 抄送至 | Zhenchao ***@***.***>***@***.***> |
| 主题 | Re: [IRMVLab/Point-Mamba] About the different between test/mIoU and test/mIoU_part (Issue #3) |

It is important to point out that there are many uncertainties in the training of the Mamba network. Our training has tried under 3 blocks of 4090 and 2 blocks of 4090 in different environments, and there is also a certain error, but almost all of them are above 73%. For your results, I would suggest that you first try to make sure that the environment is as consistent as possible with the reference we provided, and secondly, try to compare multiple training sessions. You may be able to verify this with the eval function and the CPKT we provide.Thank you!

----- 原始邮件 -----
发件人: "Zhenchao Lin" ***@***.***>
收件人: "IRMVLab/Point-Mamba" ***@***.***>
抄送: "Yu Rui Ji" ***@***.***>, "Comment" ***@***.***>
发送时间: 星期六, 2024年 3 月 30日 下午 5:46:05
主题: Re: [IRMVLab/Point-Mamba] About the different between test/mIoU and test/mIoU_part (Issue #3)

> > Hi, thank you for your work! when I trained the model in ScanNet, I found two types of mIoU in the result. Are there any differences between them? And what type of mIoU is the result in your paper?
>
> **Hello, thank you for interested in our work, and indeed our results are calculated to test_mIoU and test_mIoU_part two kinds of results, the latter used in our paper. The main difference between them is that the latter takes into account unimportant mask information such as scene background, in fact, you can read the difference between them in the segmentation.py.**

Thank you for your reply, I trained Model in ScanNet for 700 Epoch, but the best test_mIoU_part was only 70.26%, which is much lower than the results of the paper with 74.6%. I used a single RTX 3090, other configs are the same as the default. Do you think any reason caused this result?

**Comment by Aristo23333** [comment]
I didn't change this parameter to True in my actual experiment.I think maybe you are experiencing a problem with unused parameters during training and want to use this check?I seem to have encountered a similar problem, but it doesn't affect the normal training, maybe you can keep it. In addition, this parameter is inherited from Octformer, and you can also refer to his code for comparative study.
----- 原始邮件 -----
发件人: "Zhenchao Lin" ***@***.***>
收件人: "IRMVLab/Point-Mamba" ***@***.***>
抄送: "Yu Rui Ji" ***@***.***>, "Comment" ***@***.***>
发送时间: 星期一, 2024年 4 月 01日 下午 2:43:43
主题: Re: [IRMVLab/Point-Mamba] About the different between test/mIoU and test/mIoU_part (Issue #3)

As I use "find_unused_parameters: True" in your default config, the error is as follows: 
![屏幕截图 2024-04-01 143529](https://github.com/IRMVLab/Point-Mamba/assets/105730616/08fe0946-18ee-4235-a792-a1e0e735d694)

**Comment by Sylva-Lin** [comment]
> I didn't change this parameter to True in my actual experiment.I think maybe you are experiencing a problem with unused parameters during training and want to use this check?I seem to have encountered a similar problem, but it doesn't affect the normal training, maybe you can keep it. In addition, this parameter is inherited from Octformer, and you can also refer to his code for comparative study.

I use the instructions of octformer to carry the environment, I can train octformer in parallel normally, but I strictly follow the environment configuration you provided, and I have not been able to train in parallel normally, I make sure that all the configurations are consistent with those you provide, but I just can't train in parallel normally

**Comment by Sylva-Lin** [comment]
My system is Ubuntu 20.04 and Cuda uses 11.8 installed on the system

**Comment by USTCLH** [comment]
> > I didn't change this parameter to True in my actual experiment.I think maybe you are experiencing a problem with unused parameters during training and want to use this check?I seem to have encountered a similar problem, but it doesn't affect the normal training, maybe you can keep it. In addition, this parameter is inherited from Octformer, and you can also refer to his code for comparative study.
> 
> I use the instructions of octformer to carry the environment, I can train octformer in parallel normally, but I strictly follow the environment configuration you provided, and I have not been able to train in parallel normally, I make sure that all the configurations are consistent with those you provide, but I just can't train in parallel normally

Hello, [this](https://github.com/IRMVLab/Point-Mamba/issues/1#issuecomment-2040983888) may help you

**Comment by Sylva-Lin** [comment]
> > > I didn't change this parameter to True in my actual experiment.I think maybe you are experiencing a problem with unused parameters during training and want to use this check?I seem to have encountered a similar problem, but it doesn't affect the normal training, maybe you can keep it. In addition, this parameter is inherited from Octformer, and you can also refer to his code for comparative study.
> > 
> > 
> > I use the instructions of octformer to carry the environment, I can train octformer in parallel normally, but I strictly follow the environment configuration you provided, and I have not been able to train in parallel normally, I make sure that all the configurations are consistent with those you provide, but I just can't train in parallel normally
> 
> Hello, [this](https://github.com/IRMVLab/Point-Mamba/issues/1#issuecomment-2040983888) may help you

Thank you, now I can train normally with multiple GPUs. How did you find out about changing this code? Can you share your experience?
